/* أدوات مساعدة عامة + نصوص الواجهة (عربي / إنجليزي) */

export const AR_D = "٠١٢٣٤٥٦٧٨٩";
export const ar = (n: number | string) => String(n).replace(/[0-9]/g, (d) => AR_D[+d]);

export const fmtDur = (sec: number, lang = "ar") => {
  const s = Math.max(0, Math.round(sec));
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const r = s % 60;
  const p = (x: number) => String(x).padStart(2, "0");
  const out = h > 0 ? `${h}:${p(m)}:${p(r)}` : `${m}:${p(r)}`;
  return lang === "ar" ? ar(out) : out;
};

export const fmtCount = (n: number, lang = "ar") => {
  if (lang === "en")
    return n >= 1000 ? `${(n / 1000).toFixed(n >= 10000 ? 0 : 1)}K` : String(n);
  if (n >= 1000) return ar(n >= 10000 ? `${Math.round(n / 1000)}` : `${(n / 1000).toFixed(1)}`) + " ألف";
  return ar(n);
};

export const fmtAgo = (days: number, lang = "ar") => {
  if (lang === "en") {
    if (days <= 0) return "Today";
    if (days === 1) return "Yesterday";
    if (days < 7) return `${days} days ago`;
    if (days < 30) return `${Math.floor(days / 7)} wk ago`;
    return `${Math.floor(days / 30)} mo ago`;
  }
  if (days <= 0) return "اليوم";
  if (days === 1) return "أمس";
  if (days === 2) return "منذ يومين";
  if (days <= 10) return `منذ ${ar(days)} أيام`;
  if (days < 14) return `منذ ${ar(days)} يوماً`;
  if (days < 30) {
    const w = Math.floor(days / 7);
    return w === 1 ? "منذ أسبوع" : w === 2 ? "منذ أسبوعين" : `منذ ${ar(w)} أسابيع`;
  }
  const mo = Math.floor(days / 30);
  return mo === 1 ? "منذ شهر" : mo === 2 ? "منذ شهرين" : mo <= 10 ? `منذ ${ar(mo)} أشهر` : `منذ ${ar(mo)} شهراً`;
};

export const fmtMB = (mb: number) => {
  if (mb >= 1024) return ar((mb / 1024).toFixed(2)) + " جيجابايت";
  return mb >= 100 ? ar(Math.round(mb)) + " ميغابايت" : ar(mb.toFixed(1)) + " ميغابايت";
};

const DIAC = /[ً-ْٰـ]/g;
export const norm = (s: string) =>
  s
    .replace(DIAC, "")
    .replace(/[أإآٱ]/g, "ا")
    .replace(/ة/g, "ه")
    .replace(/ى/g, "ي")
    .replace(/ؤ/g, "و")
    .replace(/ئ/g, "ي")
    .toLowerCase()
    .trim();

/* ── نصوص الواجهة ── */
export const STR = {
  ar: {
    appName: "مكتبة دار الحديث الصوتية",
    appShort: "دار الحديث",
    tagline: "مكتبة صوتية إسلامية مجانية — بلا إعلانات",
    searchPh: "ابحث عن شريط، شيخ، أو سلسلة…",
    home: "الرئيسية",
    cats: "التصنيفات",
    searchT: "البحث",
    library: "مكتبتي",
    settings: "الإعدادات",
    recentlyAdded: "المُضاف حديثاً",
    mostPlayed: "الأكثر استماعاً",
    suggested: "سلاسل مقترحة",
    continueL: "استمع الآن",
    quickBrowse: "تصفح سريع",
    seeAll: "عرض الكل",
    tapes: "شريطاً",
    scholarsT: "مشايخ وقرّاء",
    seriesT: "سلسلة",
    eps: "حلقة",
    featured: "سلسلة مختارة",
    play: "تشغيل",
    resume: "استئناف",
    download: "تحميل",
    downloading: "جارٍ التحميل",
    downloaded: "محمّل",
    share: "مشاركة",
    fav: "المفضلة",
    favAdd: "أضِف للمفضلة",
    favDel: "إزالة من المفضلة",
    about: "نبذة عن الشريط",
    seriesEps: "حلقات السلسلة",
    related: "أشرطة ذات صلة",
    ep: "الحلقة",
    results: "نتيجة",
    recentSearches: "عمليات بحث سابقة",
    clear: "مسح",
    noResults: "لا توجد نتائج مطابقة",
    noResultsHint: "جرّب كلمات أخرى أو تصفح التصنيفات",
    favorites: "المفضلة",
    downloads: "التحميلات",
    playlists: "قوائم التشغيل",
    history: "الأخيرة",
    emptyFav: "لم تُضِف شيئاً بعد",
    emptyFavH: "اضغط على القلب في أي شريط لحفظه هنا",
    emptyDl: "لا توجد تحميلات",
    emptyDlH: "حمّل الأشرطة للاستماع دون اتصال",
    emptyPl: "لا توجد قوائم تشغيل",
    emptyPlH: "أنشئ قوائمك الخاصة ونظّم أشرطتك",
    newPlaylist: "قائمة جديدة",
    plName: "اسم القائمة…",
    create: "إنشاء",
    cancel: "إلغاء",
    storage: "المساحة المستخدمة",
    storageOf: "من",
    delete: "حذف",
    all: "الكل",
    sortNew: "الأحدث",
    sortOld: "الأقدم",
    sortPlayed: "الأكثر استماعاً",
    sortAlpha: "أبجدي",
    sortDur: "المدة",
    grid: "شبكة",
    list: "قائمة",
    queued: "بانتظار WiFi",
    sleep: "مؤقت النوم",
    sleepOff: "إيقاف",
    sleepEnd: "نهاية الشريط",
    min: "دقيقة",
    speed: "السرعة",
    queue: "قائمة التشغيل",
    upNext: "التالي",
    demoTag: "بث تجريبي",
    appearance: "المظهر",
    light: "فاتح",
    dark: "داكن",
    auto: "تلقائي",
    language: "اللغة",
    fontSize: "حجم الخط",
    small: "صغير",
    medium: "متوسط",
    large: "كبير",
    audioQ: "جودة الصوت",
    high: "عالية",
    med: "متوسطة",
    low: "منخفضة",
    wifiOnly: "التحميل عبر WiFi فقط",
    defSpeed: "سرعة التشغيل الافتراضية",
    defSleep: "مؤقت النوم الافتراضي",
    notif: "الإشعارات",
    notifH: "إشعار المشغل والتحكم من شاشة القفل",
    aboutApp: "عن التطبيق",
    aboutTxt:
      "تطبيق خيري تعليمي مجاني بالكامل لنشر العلم الشرعي صوتاً، دون إعلانات أو اشتراكات.",
    ver: "الإصدار",
    listenCount: "استماع",
    of: "من",
    remaining: "متبقٍ",
    done: "مكتمل",
    resumeFrom: "متابعة من",
    addToPl: "إضافة إلى قائمة",
    playAll: "تشغيل الكل",
    items: "عنصر",
    shareCopy: "تم نسخ الرابط",
    wifiNote: "سيُحمَّل تلقائياً عند توفر WiFi",
    listeningNow: "يُشغَّل الآن",
    addSeries: "إضافة سلسلة",
    addFromArch: "أضف سلسلة",
    archUrl: "رابط السلسلة",
    archUrlPh: "https://example.com/details/…",
    fetchTracks: "جلب الأشرطة",
    fetching: "جارٍ جلب الأشرطة…",
    seriesName: "اسم السلسلة",
    scholarName: "اسم الشيخ",
    section: "القسم",
    trackCount: "عدد الأشرطة",
    saveSeries: "حفظ السلسلة",
    savedSeries: "أُضيفت السلسلة بنجاح",
    mySeries: "سلاسلي",
    playQueue: "تشغيل القائمة كاملة",
    playSingle: "شريط واحد",
    modeQueue: "قائمة",
    emptySeries: "لا توجد سلاسل مضافة بعد",
    emptySeriesH: "أضف سلسلة من أرشيف الإنترنت وستظهر هنا",
    fetchErr: "تعذّر الجلب — تأكد من الرابط أو الاتصال",
    invalidUrl: "رابط غير صالح",
    selectTracks: "الأشرطة التي ستُضاف",
    deleteSeries: "حذف السلسلة",
    seriesDeleted: "حُذفت السلسلة",
    epsFound: "شريطاً",
    serverSync: "المزامنة من السحابة",
    serverSyncH: "",
    serverUrl: "عنوان الخادم",
    serverUrlPh: "http://192.168.1.5:4000",
    syncNow: "زامِن الآن",
    syncing: "جارٍ المزامنة…",
    syncOn: "المزامنة مفعلة",
    syncOff: "المزامنة معطلة",
    lastSync: "آخر مزامنة",
    syncNever: "لم تتم مزامنة بعد",
    syncDone: "اكتملت المزامنة — أُضيفت الأشرطة إلى المكتبة",
    syncFail: "تعذّرت المزامنة — تأكد من العنوان والاتصال",
    updateAvailable: "يتوفر تحديث",
    updateH: "تحديث التطبيق إلى أحدث إصدار",
    checkUpdate: "تحقق من التحديث",
    checking: "جارٍ الفحص…",
    updateNow: "تحديث الآن",
    updateDone: "تم التحميل — ثبّت التحديث من الإشعارات",
    updateFail: "تعذّر التحميل",
    latestVer: "أنت على أحدث إصدار",
  },
  en: {
    appName: "Dar Al-Hadith Audio Library",
    appShort: "Dar Al-Hadith",
    tagline: "Free Islamic audio library — no ads",
    searchPh: "Search tapes, scholars, series…",
    home: "Home",
    cats: "Categories",
    searchT: "Search",
    library: "Library",
    settings: "Settings",
    recentlyAdded: "Recently Added",
    mostPlayed: "Most Played",
    suggested: "Suggested Series",
    continueL: "Listen Now",
    quickBrowse: "Quick Browse",
    seeAll: "See all",
    tapes: "tapes",
    scholarsT: "Scholars & Reciters",
    seriesT: "Series",
    eps: "episodes",
    featured: "Featured Series",
    play: "Play",
    resume: "Resume",
    download: "Download",
    downloading: "Downloading",
    downloaded: "Downloaded",
    share: "Share",
    fav: "Favorite",
    favAdd: "Add to favorites",
    favDel: "Remove from favorites",
    about: "About this tape",
    seriesEps: "Series Episodes",
    related: "Related Tapes",
    ep: "Episode",
    results: "results",
    recentSearches: "Recent searches",
    clear: "Clear",
    noResults: "No matching results",
    noResultsHint: "Try other words or browse categories",
    favorites: "Favorites",
    downloads: "Downloads",
    playlists: "Playlists",
    history: "Recent",
    emptyFav: "Nothing saved yet",
    emptyFavH: "Tap the heart on any tape to save it here",
    emptyDl: "No downloads",
    emptyDlH: "Download tapes for offline listening",
    emptyPl: "No playlists",
    emptyPlH: "Create your own lists and organize tapes",
    newPlaylist: "New playlist",
    plName: "Playlist name…",
    create: "Create",
    cancel: "Cancel",
    storage: "Storage used",
    storageOf: "of",
    delete: "Delete",
    all: "All",
    sortNew: "Newest",
    sortOld: "Oldest",
    sortPlayed: "Most played",
    sortAlpha: "A–Z",
    sortDur: "Duration",
    grid: "Grid",
    list: "List",
    queued: "Waiting for WiFi",
    sleep: "Sleep timer",
    sleepOff: "Off",
    sleepEnd: "End of tape",
    min: "min",
    speed: "Speed",
    queue: "Queue",
    upNext: "Up next",
    demoTag: "Demo stream",
    appearance: "Appearance",
    light: "Light",
    dark: "Dark",
    auto: "Auto",
    language: "Language",
    fontSize: "Font size",
    small: "Small",
    medium: "Medium",
    large: "Large",
    audioQ: "Audio quality",
    high: "High",
    med: "Medium",
    low: "Low",
    wifiOnly: "Download on WiFi only",
    defSpeed: "Default playback speed",
    defSleep: "Default sleep timer",
    notif: "Notifications",
    notifH: "Player notification & lockscreen controls",
    aboutApp: "About",
    aboutTxt:
      "A fully free educational charity app spreading authentic Islamic knowledge in audio. No ads, no subscriptions.",
    ver: "Version",
    listenCount: "plays",
    of: "of",
    remaining: "left",
    done: "Completed",
    resumeFrom: "Resume from",
    addToPl: "Add to playlist",
    playAll: "Play all",
    items: "items",
    shareCopy: "Link copied",
    wifiNote: "Auto-download on WiFi",
    listeningNow: "Now playing",
    addSeries: "Add series",
    addFromArch: "Add a series",
    archUrl: "Series link",
    archUrlPh: "https://example.com/details/…",
    fetchTracks: "Fetch tracks",
    fetching: "Fetching tracks…",
    seriesName: "Series name",
    scholarName: "Scholar name",
    section: "Category",
    trackCount: "Number of tracks",
    saveSeries: "Save series",
    savedSeries: "Series added successfully",
    mySeries: "My series",
    playQueue: "Play full queue",
    playSingle: "Single track",
    modeQueue: "Queue",
    emptySeries: "No series added yet",
    emptySeriesH: "Add a series from the Internet Archive and it will appear here",
    fetchErr: "Fetch failed — check the link or connection",
    invalidUrl: "Invalid link",
    selectTracks: "Tracks to add",
    deleteSeries: "Delete series",
    seriesDeleted: "Series deleted",
    epsFound: "tracks",
    serverSync: "Cloud sync",
    serverSyncH: "Fetch published library tapes from the Firebase database — works on any phone without a local server",
    serverUrl: "Server address",
    serverUrlPh: "http://192.168.1.5:4000",
    syncNow: "Sync now",
    syncing: "Syncing…",
    syncOn: "Sync enabled",
    syncOff: "Sync disabled",
    lastSync: "Last sync",
    syncNever: "Never synced",
    syncDone: "Sync complete — tapes added to the library",
    syncFail: "Sync failed — check the address and connection",
    updateAvailable: "Update available",
    updateH: "Update the app to the latest version",
    checkUpdate: "Check for updates",
    checking: "Checking…",
    updateNow: "Update now",
    updateDone: "Download complete — install from notifications",
    updateFail: "Download failed",
    latestVer: "You are on the latest version",
  },
} as const;

export type Lang = keyof typeof STR;
export type Strings = Record<keyof (typeof STR)["ar"], string>;
